services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Backend
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - DB_NAME=ecommerce
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=mysecretkey
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ecommerce_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
